apiVersion: v1
kind: Service
metadata:
  name: isaac-server-sim
spec:
  selector:
    name: isaac-server
  ports:
  - name: simulation-port
    port: 2460
    protocol: TCP
    targetPort: 2460
  type: NodePort 
